server:
  port: 2000

spring:
#  mvc:
#    view:
#      prefix: /views/
#      suffix: .html

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/API_assignment_1
    username: root
    password: password123

  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      show_sql: true
    hibernate:
      ddl-auto: update

#logging:
#  level:
#    org:
#      springframework: debug