server:
  port: 2323

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/API_assignment_1
    username: root
    password: password123

  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      show_sql: true
    hibernate:
      ddl-auto: update